site_name: Csound 7 Manual
site_url: https://csound7_manual
theme:
  name: material
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
  features:
    - navigation.footer

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: 'docs/'
  - pymdownx.superfences
  - attr_list:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: 'index.md'
  - Preface:
    - What's New in Csound 7: 'intro-whats-new-in-csound-7.md'
    - Historical Preface: 'intro-historic-preface.md'
    - History of the Manual: 'intro-history-of-the-manual.md'
    - Copyright Notice: 'intro-copyright-notice.md'
  - Invoking Csound:
    - How Csound Works: 'invoke-how-csound-works.md'
    - The `csound` Command: 'invoke-the-csound-command.md'
    - The `.csd` File Format: 'invoke-the-csd-file-format.md'
    - Csound Options (flags) Alphabetically: 'invoke-cs-options-alphabetically.md'
    - Csound Options (flags) by Category: 'invoke-cs-options-by-category.md'
    - Environment Variables: 'invoke-environment-variables.md'
    - Order of Precedence: 'invoke-order-of-precedence.md'
  - Syntax of the Orchestra:
    - Header Statements and Global Space: 'orc-header-statements.md'
    - Instruments: 'orc-instruments.md'
    - Data Types and Variables: 'orc-data-types.md'
    - Macros: 'orc-macros.md'
    - User Defined Opcodes (UDO): 'orc-user-defined-opcodes.md'
    - Traditional and Functional Code: 'orc-traditional-functional-code.md'
  - Syntax of the Score:
    - Parameter Fields: 'score/parameter-fields.md'
    - Durations in Instrument Events: 'score/note-durations.md'
    - Preprocessing: 'score/preproc.md'
    - List of Statements: 'score/statemnt.md'
    - GEN routines: 'score/genroutines.md'
    - Macros: 'score/macros.md'
    - Included Files: 'score/mult.md'
    - Expressions: 'score/eval.md'
    - Scripts: 'score/scripts.md'
  - Miscellanea:
    - Nomenclature: 'misc-nomenclature.md'
    - Links: 'misc-links.md'
    - UDP Server: 'misc-udp-server.md'
    - Real-Time Audio: 'misc-rt-audio.md'
  - Opcodes Overview:
    - Signal Generators:
      - Additive Synthesis/Resynthesis: 'siggen/additive.md'
      - Basic Oscillators: 'siggen/basic.md'
      - Dynamic Spectrum Oscillators: 'siggen/dynamic.md'
      - FM Synthesis: 'siggen/fmsynth.md'
      - Granular Synthesis: 'siggen/granular.md'
      - Hyper Vectorial Synthesis: 'siggen/hvs.md'
      - Linear and Exponential Generators: 'siggen/lineexp.md'
      - Envelope Generators: 'siggen/envelope.md'
      - Models and Emulations: 'siggen/models.md'
      - Phasors: 'siggen/phasors.md'
      - Random (Noise) Generators: 'siggen/random.md'
      - Sample Playback and Soundfonts: 'siggen/sample.md'
      - Scanned Synthesis: 'siggen/scantop.md'
      - Table Access: 'siggen/tableacc.md'
      - Wave Terrain Synthesis: 'siggen/waveterr.md'
      - Waveguide Physical Modeling: 'siggen/wavguide.md'
    - Signal Input and Output:
      - File Input and Output: 'sigio/fileio.md'
      - Signal Input: 'sigio/input.md'
      - Signal Output: 'sigio/output.md'
      - Software Bus: 'sigio/softbus.md'
      - Printing and Display: 'sigio/pdisplay.md'
      - Sound Files Queries: 'sigio/queries.md'
    - Signal Modifiers:
      - Amplitude Modifiers and Dynamic processing: 'sigmod/ampmod.md'
      - Convolution and Morphing: 'sigmod/conmorph.md'
      - Delay: 'sigmod/delayops.md'
      - Panning and Spatialization: 'sigmod/panspatl.md'
      - Reverberation: 'sigmod/reverbtn.md'
      - Sample Level Operators: 'sigmod/sample.md'
      - Signal Limiters: 'sigmod/siglimit.md'
      - Special Effects: 'sigmod/speciale.md'
      - Standard Filers: 'sigmod/standard.md'
      - Specialized Filters: 'sigmod/speciali.md'
      - Waveguides: 'sigmod/wavguide.md'
      - Waveshaping and Phase Distortion: 'sigmod/wavshape.md'
    - Instrument Control:
      - Clock Control: 'control/clockctl.md'
      - Conditional Values: 'control/conditional.md'
      - Duration Control Statements: 'control/durctl.md'
      - Instrument Invocation: 'control/invocat.md'
      - Program Flow Control: 'control/pgmctl.md'
      - Realtime Performance Control: 'control/realtime.md'
      - Initialization and Reinitialization: 'control/reinitn.md'
      - Sensing and Control: 'control/sensing.md'
      - Stacks: 'control/stacks.md'
      - Sub-instrument Control: 'control/subinstr.md'
      - Time Reading: 'control/timeread.md'
    - Function Table Control:
      - 'table/top.md'
      - Table Queries: 'table/queries.md'
      - Read/Write Operations: 'table/readwrit.md'
      - Table Reading with Dynamic Selection: 'table/select.md'
    - Mathematical Operations:
      - Amplitude Converters: 'math/amp.md'
      - Arithmetic and Logic Operations: 'math/artlogic.md'
      - Comparators and Accumulators: 'sigmod/compaccum.md'
      - Mathematical Functions: 'math/mathfunc.md'
      - Opcode Equivalents of Functions: 'math/opeqfunc.md'
      - Random Functions: 'math/rndfunc.md'
      - Trigonometric Functions: 'math/trig.md'
      - Linear Algebra Opcodes: 'math/linearalgebra.md'
      - Array Opcodes: 'math/array.md'
    - Pitch Converters:
      - Functions: 'pitch/funcs.md'
      - Tuning Opcodes: 'pitch/tuning.md'
    - Real-time MIDI Support:
      - 'midi/top.md'
      - Virtual MIDI Keyboard: 'midi/virtual.md'
      - MIDI input and Initialization: 'midi/input.md'
      - MIDI Message Output: 'midi/output.md'
      - Generic Input and Output: 'midi/generic.md'
      - Converters: 'midi/convert.md'
      - Event Extenders: "midi/extender.md"
      - Note-on/Note-off Output: "midi/onoff.md"
      - MIDI/Score Interoperability opcodes: "midi/interop.md"
      - System Realtime Messages: 'midi/realtime.md'
      - Slider Banks: 'midi/sliderbk.md'
    - Spectral processing:
      - 'spectral/top.md'
      - Short-time Fourier Transform (STFT) Resynthesis: 'spectral/stft.md'
      

