theme:
  name: readthedocs
  
site_name: Csound 7 Manual

nav:
  - Home: 'index.md'
  - Introduction:
    - What's New in Csound 7: 'intro-whats-new-in-csound-7.md'
    - Historical Preface: 'intro-historic-preface.md'
    - History of the Manual: 'intro-history-of-the-manual.md'
    - Copyright Notice: 'intro-copyright-notice.md'
  - 'Invoking Csound':
    - How Csound Works: 'invoke-how-csound-works.md'
    - The `.csd` File Format: 'invoke-the-csd-file-format.md'
    - The `csound` Command: 'invoke-the-csound-command.md'
    - Csound Options (flags) Alphabetically: 'invoke-cs-options-alphabetically.md'
    - Csound Options (flags) by Category: 'invoke-cs-options-by-category.md'
    - Environment Variables: 'invoke-environment-variables.md'
    - Order of Precedence: 'invoke-order-of-precedence.md'
  - Syntax of the Orchestra:
    - Header Statements and Global Space: 'orc-header-statements.md'
    - Instruments: 'orc-instruments.md'
    - Data Types and Variables: 'orc-data-types.md'
    - Macros: 'orc-macros.md'
    - User Defined Opcodes (UDO): 'orc-user-defined-opcodes.md'
    - Traditional and Functional Code: 'orc-traditional-functional-code.md'
  - Syntax of the Score:
    - Parameter Fields: 'sco-parameter-fields.md'
    - Preprocessing: 'sco-preprocessing.md'
    - Statements: 'sco-statements.md'
    - Macros: 'sco-macros.md'
    - Included Files: 'sco-included-files.md'
    - Expressions: 'sco-expressions.md'
